[package]
name = "bsnark"
version = "0.1.0"
authors = ["alexander <mail@fomalhaut.su>"]

[dependencies]
rand = "0.4"
ff = { version = "0.4", features = ["derive"] }
pairing = "0.14"
bellman = "0.1.0"
